### ISSUE TITLE
Add some way to set weighting

### ISSUE THREAD

**Issue by kychum** [kychum/course-scheduler#1]
The weights w_{minfilled}, w_{pref}, w_{pair} and w_{secdiff} need to be configurable when running the program. We could either set these as command-line flags or via some config file (preferred)

**Comment by kychum** [comment]
Initially I was hoping to use JSON for a config file but that would require JSONP or a similar library. If the hassle is worth it then that's fine, otherwise we could use XML since that's built into the language already.

**Comment by TerminalVelociraptor** [comment]
I'm wondering whether doing XML + DTD or JSON just for a few weight values is adding too much
 unnecessary complexity . If it's just a few different weight values what's wrong with just sticking them in a text file, or passing in as command line switches.

**Comment by kychum** [comment]
It might be a bit overkill now that I look at it. For some reason I thought there were a few more things to configure earlier. Ideally something with a simple format that already has an implemented parser would have saved us the trouble of actually parsing a file hence the original JSON suggestion, but a text file works fine too. Command line switches might be annoying to change on the fly if he asks us to rerun the same instance with different weights a lot but would give us a bit of flexibility on how we do things during the presentation.

**Comment by kychum** [comment]
For now there'll be a config.ini that sets these values along with the main program.
